import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: {
          DEFAULT: "hsl(var(--border-default))",
          subtle: "hsl(var(--border-subtle))",
          strong: "hsl(var(--border-strong))",
          focus: "hsl(var(--border-focus))",
          error: "hsl(var(--border-error))",
        },
        input: {
          DEFAULT: "hsl(var(--input))",
          inset: "hsl(var(--bg-inset))",
        },
        ring: {
          DEFAULT: "hsl(var(--ring))",
        },
        background: {
          DEFAULT: "hsl(var(--bg-page))",
          page: "hsl(var(--bg-page))",
          surface: "hsl(var(--bg-surface))",
          elevated: "hsl(var(--bg-elevated))",
          inset: "hsl(var(--bg-inset))",
          hover: "hsl(var(--bg-hover))",
          active: "hsl(var(--bg-active))",
          tooltip: "hsl(var(--bg-tooltip))",
        },
        foreground: {
          DEFAULT: "hsl(var(--text-primary))",
          primary: "hsl(var(--text-primary))",
          secondary: "hsl(var(--text-secondary))",
          tertiary: "hsl(var(--text-tertiary))",
          inverse: "hsl(var(--text-inverse))",
          link: "hsl(var(--text-link))",
          success: "hsl(var(--text-success))",
          warning: "hsl(var(--text-warning))",
          error: "hsl(var(--text-error))",
        },
        primary: {
          50: "hsl(var(--color-primary-50))",
          100: "hsl(var(--color-primary-100))",
          200: "hsl(var(--color-primary-200))",
          300: "hsl(var(--color-primary-300))",
          400: "hsl(var(--color-primary-400))",
          500: "hsl(var(--color-primary-500))",
          600: "hsl(var(--color-primary-600))",
          700: "hsl(var(--color-primary-700))",
          800: "hsl(var(--color-primary-800))",
          900: "hsl(var(--color-primary-900))",
          DEFAULT: "hsl(var(--color-primary-500))",
        },
        secondary: {
          50: "hsl(var(--color-secondary-50))",
          100: "hsl(var(--color-secondary-100))",
          500: "hsl(var(--color-secondary-500))",
          600: "hsl(var(--color-secondary-600))",
          700: "hsl(var(--color-secondary-700))",
          DEFAULT: "hsl(var(--color-secondary-500))",
        },
        success: {
          DEFAULT: "hsl(var(--color-success))",
          bg: "hsl(var(--color-success-bg))",
        },
        warning: {
          DEFAULT: "hsl(var(--color-warning))",
          bg: "hsl(var(--color-warning-bg))",
        },
        error: {
          DEFAULT: "hsl(var(--color-error))",
          bg: "hsl(var(--color-error-bg))",
        },
        info: {
          DEFAULT: "hsl(var(--color-info))",
          bg: "hsl(var(--color-info-bg))",
        },
        neutral: {
          50: "hsl(var(--color-neutral-50))",
          100: "hsl(var(--color-neutral-100))",
          150: "hsl(var(--color-neutral-150))",
          200: "hsl(var(--color-neutral-200))",
          300: "hsl(var(--color-neutral-300))",
          400: "hsl(var(--color-neutral-400))",
          500: "hsl(var(--color-neutral-500))",
          600: "hsl(var(--color-neutral-600))",
          700: "hsl(var(--color-neutral-700))",
          800: "hsl(var(--color-neutral-800))",
          900: "hsl(var(--color-neutral-900))",
          950: "hsl(var(--color-neutral-950))",
        },
        rag: {
          red: "hsl(var(--rag-red))",
          "red-bg": "hsl(var(--rag-red-bg))",
          amber: "hsl(var(--rag-amber))",
          "amber-bg": "hsl(var(--rag-amber-bg))",
          green: "hsl(var(--rag-green))",
          "green-bg": "hsl(var(--rag-green-bg))",
        },
      },
      borderRadius: {
        none: "0",
        sm: "var(--radius-sm)",
        DEFAULT: "var(--radius-md)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        full: "var(--radius-full)",
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "SF Mono", "Fira Code", "Cascadia Code", "monospace"],
        "sans-arabic": ["IBM Plex Sans Arabic", "Noto Naskh Arabic", "Inter", "sans-serif"],
        "sans-ethiopic": ["Noto Sans Ethiopic", "Inter", "sans-serif"],
      },
      fontSize: {
        xs: ["12px", { lineHeight: "16px", letterSpacing: "0.02em" }],
        sm: ["14px", { lineHeight: "20px", letterSpacing: "0.01em" }],
        base: ["16px", { lineHeight: "24px", letterSpacing: "0" }],
        lg: ["18px", { lineHeight: "28px", letterSpacing: "0" }],
        xl: ["20px", { lineHeight: "28px", letterSpacing: "-0.01em" }],
        "2xl": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em" }],
        "3xl": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em" }],
        "4xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em" }],
        "5xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em" }],
        "6xl": ["60px", { lineHeight: "72px", letterSpacing: "-0.03em" }],
      },
      fontWeight: {
        normal: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
      },
      spacing: {
        "1": "4px",
        "2": "8px",
        "3": "12px",
        "4": "16px",
        "5": "20px",
        "6": "24px",
        "8": "32px",
        "10": "40px",
        "12": "48px",
        "16": "64px",
        "20": "80px",
      },
      boxShadow: {
        "1": "0 1px 2px hsl(var(--shadow-color) / 0.06), 0 1px 3px hsl(var(--shadow-color) / 0.10)",
        "2": "0 2px 4px hsl(var(--shadow-color) / 0.06), 0 2px 6px hsl(var(--shadow-color) / 0.08)",
        "3": "0 4px 8px hsl(var(--shadow-color) / 0.08), 0 4px 12px hsl(var(--shadow-color) / 0.06)",
        "4": "0 8px 16px hsl(var(--shadow-color) / 0.10), 0 6px 20px hsl(var(--shadow-color) / 0.06)",
        "5": "0 12px 24px hsl(var(--shadow-color) / 0.12), 0 8px 32px hsl(var(--shadow-color) / 0.08)",
      },
      zIndex: {
        base: "0",
        dropdown: "100",
        sticky: "200",
        overlay: "300",
        modal: "400",
        toast: "500",
        tooltip: "600",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "fade-out": {
          from: { opacity: "1" },
          to: { opacity: "0" },
        },
        "slide-in-from-right": {
          from: { transform: "translateX(100%)" },
          to: { transform: "translateX(0)" },
        },
        "slide-out-to-right": {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(100%)" },
        },
        "slide-in-from-top": {
          from: { transform: "translateY(-100%)" },
          to: { transform: "translateY(0)" },
        },
        "skeleton-pulse": {
          "0%, 100%": { opacity: "0.1" },
          "50%": { opacity: "0.15" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.2s ease-out",
        "fade-out": "fade-out 0.15s ease-in",
        "slide-in-from-right": "slide-in-from-right 0.25s ease-out",
        "slide-out-to-right": "slide-out-to-right 0.2s ease-in",
        "skeleton-pulse": "skeleton-pulse 1.5s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
