import type { Metadata, Viewport } from 'next';
import { Inter, Sora } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
});

const sora = Sora({
  subsets: ['latin'],
  variable: '--font-display',
  display: 'swap',
});

/** iOS launch screens (generated by scripts/brand-assets.sh). */
const LAUNCH_SCREENS: [number, number, number][] = [
  [375, 667, 2],
  [414, 896, 2],
  [375, 812, 3],
  [390, 844, 3],
  [393, 852, 3],
  [414, 896, 3],
  [428, 926, 3],
  [430, 932, 3],
];

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || 'https://merline.jrecc.org'),
  title: {
    template: '%s · Merline',
    default: 'Merline — Research Intelligence',
  },
  description:
    'Qualitative research workspace: interview guides, consent, field recording, transcripts and evidence-linked findings.',
  applicationName: 'Merline',
  manifest: '/manifest.json',
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: 'any' },
      { url: '/icons/favicon-16.png', sizes: '16x16', type: 'image/png' },
      { url: '/icons/favicon-32.png', sizes: '32x32', type: 'image/png' },
      { url: '/icons/favicon-48.png', sizes: '48x48', type: 'image/png' },
    ],
    apple: [{ url: '/icons/apple-touch-icon.png', sizes: '180x180' }],
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'Merline',
    startupImage: LAUNCH_SCREENS.map(([w, h, r]) => ({
      url: `/splash/launch-${w * r}x${h * r}.png`,
      media: `(device-width: ${w}px) and (device-height: ${h}px) and (-webkit-device-pixel-ratio: ${r}) and (orientation: portrait)`,
    })),
  },
  formatDetection: { telephone: false },
  openGraph: {
    type: 'website',
    siteName: 'Merline',
    title: 'Merline — Research Intelligence',
    description: 'Qualitative research workspace with evidence-linked findings.',
    images: [{ url: '/brand/og-image.png', width: 1200, height: 630, alt: 'Merline' }],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Merline — Research Intelligence',
    description: 'Qualitative research workspace with evidence-linked findings.',
    images: ['/brand/og-image.png'],
  },
  // Private, authenticated product: nothing here should be indexed.
  robots: { index: false, follow: false },
};

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#F7F9FC' },
    { media: '(prefers-color-scheme: dark)', color: '#0E1422' },
  ],
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${sora.variable} font-sans antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
