'use client';

import { useRouter } from 'next/navigation';
import type { ColumnDef } from '@tanstack/react-table';
import { DataTable } from '@/components/shared/data-table';
import { Badge } from '@/components/ui/badge';
import { formatDate } from '@/lib/utils';
import type { Report } from '@/types/report';

const statusVariant: Record<string, 'default' | 'primary' | 'success' | 'warning' | 'error'> = {
  draft: 'default',
  generating: 'warning',
  completed: 'success',
  failed: 'error',
};

interface ReportTableProps {
  data: Report[];
  isLoading?: boolean;
  isError?: boolean;
  error?: Error | null;
  onRetry?: () => void;
}

export function ReportTable({ data, isLoading, isError, error, onRetry }: ReportTableProps) {
  const router = useRouter();

  const columns: ColumnDef<Report>[] = [
    {
      accessorKey: 'title',
      header: 'Title',
      cell: ({ row }) => (
        <span className="font-medium cursor-pointer hover:text-primary" onClick={() => router.push(`/reports/${row.original.id}`)}>
          {row.original.title}
        </span>
      ),
    },
    {
      accessorKey: 'report_type',
      header: 'Type',
      cell: ({ row }) => (
        <span className="capitalize">{row.original.report_type.replace(/_/g, ' ')}</span>
      ),
    },
    {
      accessorKey: 'status',
      header: 'Status',
      cell: ({ row }) => (
        <Badge variant={statusVariant[row.original.status] || 'default'} size="sm">
          {row.original.status}
        </Badge>
      ),
    },
    {
      accessorKey: 'generated_by.name',
      header: 'Generated By',
      cell: ({ row }) => <span>{row.original.generated_by?.name || '-'}</span>,
    },
    {
      accessorKey: 'generated_at',
      header: 'Generated',
      cell: ({ row }) => (
        <span className="text-foreground-secondary">
          {row.original.generated_at ? formatDate(row.original.generated_at) : '-'}
        </span>
      ),
    },
  ];

  return (
    <DataTable
      columns={columns}
      data={data}
      isLoading={isLoading}
      isError={isError}
      error={error}
      onRetry={onRetry}
      searchable
      searchPlaceholder="Search reports..."
      emptyTitle="No reports yet"
      emptyDescription="Generate your first report to get started."
    />
  );
}
